### PR TITLE
bugfixes: wrong #ifdef sequence, bool function misses return

### PR DESCRIPTION
**Pull request by ewyll**
Some typos I encountered, at least they seem so.

### CODE REVIEW

**Comment by skarlsson** [comment]
Well, thanks - it was a bug even if you closed the pull request - fixed.

However I realize you are compiling under windows - I haven't done that for
several months so I might have some more bashing to come...

2017-12-06 15:37 GMT+01:00 Tomislav Gracin <notifications@github.com>:

**Comment by ewyll** [comment]
I closed it because you fixed an issue I submitted - so I wanted to re-submitt a clean pull request so you don't have to solve conflicts yourself. But then, you solved both of them without me :).

Yes, I am trying to build it under Windows, and there are/were some problems. For example, in latest version `avro_serves.h` you include files which aren't in repo:
```
#include <avro/Encoder.hh>
#include <avro/Decoder.hh>
#include <avro/Compiler.hh>
#include <avro/Generic.hh>
#include <avro/Specific.hh>```

So now I am focusing on v0.7.6

**Comment by skarlsson** [comment]
Those are in avro. (apache) . I'll try to build on windows tomorrow.

**Comment by skarlsson** [comment]
btw avro was required a couple of releases ago so 0.7.6 will not help you.
I have the build instructions for windows somewhere and I get them
tomorrow. I dropped windows in June and switched to Linux and clion

2017-12-06 22:55 GMT+01:00 Svante Karlsson <svante.karlsson@csi.se>:

> Those are in avro. (apache) . I'll try to build on windows tomorrow.
>

**Comment by skarlsson** [comment]
forgot to say, I appreciate support! (even if it's windows)

2017-12-07 0:45 GMT+01:00 Svante Karlsson <svante.karlsson@csi.se>:

> btw avro was required a couple of releases ago so 0.7.6 will not help you.
> I have the build instructions for windows somewhere and I get them
> tomorrow. I dropped windows in June and switched to Linux and clion
>
> 2017-12-06 22:55 GMT+01:00 Svante Karlsson <svante.karlsson@csi.se>:
>
>> Those are in avro. (apache) . I'll try to build on windows tomorrow.
>>

**Pull request closed without merging**
